### ISSUE TITLE
[DataCap Application]  Digital Earth Africa

### ISSUE THREAD

**Issue by nike-mp** [nicelove666/Allocator-Pathway-IPFSTT#17]
### Version

1

### DataCap Applicant

FileTech

### Project ID

FileTech-01

### Data Owner Name

Digital Earth Africa

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.digitalearthafrica.org/

### Social Media Handle

Twitter: https://twitter.com/DEarthAfrica Youtube: https://www.youtube.com/channel/UCBasD3Dz-TdQTRoyG30kVVw

### Social Media Type

WeChat

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1nqded3y6ep6hssouvq5iyvud7rj2dku6b7vndta

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileTech focuses on providing excellent data storage solutions. We have a passionate and knowledgeable team with extensive experience and expertise in the field of data storage. Whether it's data storage, data management, data recovery, or data center design and construction, we possess abundant technical capabilities and solutions.

At FileTech, we understand the importance of data in modern businesses. We not only offer high-performance data storage devices and solutions, but also provide comprehensive data management tools to help clients efficiently organize, classify, and protect their data assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Landsat scenes and metadata. DE Africa provides data from Landsat 5, 7 and 8 satellites, including historical observations dating back to late 1980s and regularly updated new acquisitions.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://www.digitalearthafrica.org/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02984282 
f02942808
f02894875
f02370792 
f01025366
f0122215 
f0427989
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for applying to me and please answer these questions:

If you are a data preparer. What is your location (Country/Region)

If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

**Comment by nike-mp** [comment]
If you are a data preparer. What is your location (Country/Region)
China

If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
We carry out secondary development based on https://github.com/karust/gogetcrawl. After downloading a batch of data from Amazon Web Services S3, it will automatically process the packaging and generate the car file. As long as the same download parameters are set, it can be downloaded and Generate car files with the same piececid to ensure that different SPs can download and encapsulate the same file to ensure that the data backup meets the requirements. After the car file is generated, a corresponding unit data will be generated at the same time, including filename, data_cid, piece_cid, piece_size and other information and written into the csv file. The csv file is the datacap distribution file that will be used later, and the file name is the downloaded The marker name and starting position of the dataset. Based on the metadata file, you can tell which portion of the total data set is saved by each LDN. The data download can be executed directly on the SP's device, or we can mail it to the SP through the hard disk after processing.

Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
This website has a lot of data. Although some SPs store data, only a part of it is stored. We hope to help Filecoin store the data of the entire website.

**Comment by nike-mp** [comment]
Dear, I hope you can help us, we need your help very much.

**Comment by nicelove666** [comment]
Thank you for your application, @nike-mp

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
State the reason for the assignment:
First, I did due diligence and found that this applicant applied with multiple accounts, such as DAYOU and ChuangShi, and the data subjects used were different.
Second, I have met with customers offline, visited their company environment, and learned about their company’s technical capabilities and solutions. They have been working for Filecoin for three years. As technical staff, we recognize their efforts.
Third, I checked their search through lassie and boost, and it is indeed searchable.

**Comment by nicelove666** [comment]
![142d7424f8f03823c97548ae1f22dc09](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/27197fed-4ce7-4937-ae1e-64ed579947ba)
![79b6cacdf0b94c7b3111f2d84c6120cc](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/39f37c46-4996-469a-a1f6-d624638cfc25)
![f3cd685f2d7681c25e015ab23f254f5f](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/80b58cf4-823b-40fa-befa-ce276ed63e2a)
![0aa758d2e9f1b58e3a353254cd54646d](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/97220df7-d72e-49e9-9a0e-9a9696183b66)
![da985adff68bb338508eec4d4cfe4ddb](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/3e486ddd-8fad-4394-8b9a-8384368f5c05)

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
I hope to see an improvement in your retrieval data on spark.Please list relevant solutions, otherwise it will not be updated later.

**Comment by nike-mp** [comment]
checker:manualTrigger

**Comment by nike-mp** [comment]
We are seeking more DCs to verify our latest technical solutions and hope to get updates.

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin
