### ISSUE TITLE
[DataCap Application]  XuTing

### ISSUE THREAD

**Issue by gimims** [nicelove666/Allocator-Pathway-IPFSTT#20]
### Version

1

### DataCap Applicant

XuTing

### Project ID

001

### Data Owner Name

XuTing

### Data Owner Country/Region

United States

### Data Owner Industry

Arts & Recreation

### Website

no

### Social Media Handle

no

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

10TiB

### Expected size of single dataset (one copy)

2.5TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

2TiB

### On-chain address for first allocation

f1hsk6xqodhe4wpwoxchzusj26epyonygg6zihn6q

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Personal data, photos, information, want to be stored on the FIlecoin network
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Personal data, photos, information, want to be stored on the FIlecoin network
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
no
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02894875
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application. Please modify the "title". Which organization do you represent and what kind of data do you want to store?

**Comment by nicelove666** [comment]
Is there any update here? If not, please close the application.

**Comment by gimims** [comment]
I do not represent any organization, I am an individual who loves Filecoin. I have many precious photos in the past twenty years that I want to store in Filecoin. We only need 10T of storage space. I hope you can give me 1TiB of capacity for testing first. Thank you.

**Comment by nicelove666** [comment]
You just want 1tib, right?

**Comment by nicelove666** [comment]
Are you ready now? Do you need any help from me? We can have a video call and I will be happy to help you.

**Comment by gimims** [comment]
I am ready now and will start it after May 1st International Labor Day. I hope to get your help.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin
