### ISSUE TITLE
[DataCap Application] IGSR

### ISSUE THREAD

**Issue by szalongdzyxgs** [nicelove666/Allocator-Pathway-IPFSTT#27]
### Version

1

### DataCap Applicant

Quasar

### Project ID

Quasar-1

### Data Owner Name

he International Genome Sample Resource

### Data Owner Country/Region

China

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.internation

### Social Media Handle

https://www.internation

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

6PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1xyhrgnsmgkfz7u2rbxpewzidpi2sgxf5rwozuhi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Quasar's most notable strength lies in its deep expertise in IPFS technology. The company's core technical team has over 3 years of IPFS development experience and a thorough understanding of the principles and applications of distributed storage systems. They have leveraged IPFS to build Quasar's own data management platform, enabling fast, secure, and scalable data storage and sharing.

Bolstered by its exceptional IPFS capabilities, Quasar provides clients with a one-stop solution covering data collection, cleaning, analysis, and visualization. The company's data analysis tools are highly acclaimed for their ability to help clients uncover valuable insights hidden within their data. Quasar also offers blockchain-based data auditing and copyright management services to ensure the security and traceability of clients' data assets.

Looking ahead, Quasar will continue to focus on the research and application of IPFS and other cutting-edge technologies, striving to become a leading provider of data innovation services in Europe. Guided by client needs, the company will constantly optimize its products and services, injecting new momentum into the digital transformation of enterprises.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The 1000 Genomes Project created a catalogue of common human genetic variation, using openly consented samples from people who declared themselves to be healthy. The reference data resources generated by the project remain heavily used by the biomedical science community.

The International Genome Sample Resource (IGSR) maintains and shares the human genetic variation resources built by the 1000 Genomes Project. We also update the resources to the current reference assembly, add new data sets generated from the 1000 Genomes Project samples and add data from projects working with other openly consented samples.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

United States

### Please share a sample of the data

```text
https://www.internationalgenome.org/data
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
Polaris    f02951213   Singapore 
ShenSuanCloud  f03035686   Nanchang, Jiangxi, CN
CoffeeCloud  f03086293   Hong Kong
CoffeeCloud  f03136267   Hong Kong
Round Arithmetic    f02200472   Chengdu, Sichuan, CN
Individual    f02956383    Hong Kong
Lucky Star     f03068013   Hong Kong

```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:
1. You need to provide comprehensive SP information, including SP, geographical location, and company name.
2. Why did you choose this data set, what data did you plan to download, and how much data did you download.
3. Can you satisfy spark retrieval and store unseal files?

**Comment by szalongdzyxgs** [comment]
Hello, we plan to cooperate with 6 SPs, from 4 companies and one individual.
Polaris f02951213 Singapore
ShenSuanCloud f03035686 Nanchang, Jiangxi, CN
CoffeeCloud f03086293 Hong Kong
CoffeeCloud f03136267 Hong Kong
Round Arithmetic f02200472 Chengdu, Sichuan, CN
Individual f02956383 Hong Kong

From my observation, no one has stored this dataset on the Filecoin network, https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/pilot_data/data/
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1/technical/working/20110216_broad_exome_bams/
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase1
https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3
We have now completed the downloading and archiving indexing of the above part of the data set. The total source data files are about 110T, the calculated car file is about 180T, and 6 backups are 1080T. We call Aspera through a script to download files, and perform archiving and car file calculations for each downloaded part according to the preset process.

We require SPs to actively research Spark and store unseal files to satisfy retrieval.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by szalongdzyxgs** [comment]
The data has not been updated, so we will contact the SP immediately, list the cooperating SPs, and check the retrieval status. @nicelove666

**Comment by szalongdzyxgs** [comment]
![WechatIMG47](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/dd3c2583-fb08-4835-9cef-72a46dd333d0)
![WechatIMG48](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/5e444bce-5d07-4135-aa23-8d16a731861b)
![WechatIMG49](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/3b6b088b-582a-469e-bac6-eaceddc8c55e)
![WechatIMG50](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/ce99f950-c73c-4c91-ace0-18608648dbac)
![WechatIMG65](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/5da65d41-f2c3-4c97-a068-8bf983c2f35e)
![WechatIMG53](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/76349cac-564b-4b0d-b3f2-ae5fab7f2fca)

**Comment by szalongdzyxgs** [comment]
We have disclosed 6 SPs, and we have also cooperated with 6 SPs, all of which support boost retrieval, and some of them support Spark retrieval. There are only 256T in the first round. We look forward to you bringing us another round. Thank you!

**Comment by nicelove666** [comment]
https://github.com/nicelove666/Allocator-Pathway-IPFSTT/issues/27

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
We looked at the data, can you explain why a new SP was added?<img width="821" alt="WechatIMG22108" src="https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/c19d26c4-de78-4aba-90ef-1f5c87c62931">
<img width="909" alt="WechatIMG22110" src="https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/79055995-d3a0-4535-b19e-37940223ed5c">

**Comment by szalongdzyxgs** [comment]
Hi, dear  @nicelove666 , the SP we cooperate with has added a f03068013, they have just been established. Located in Hong Kong, the company is affiliated with Lucky Star. We have modified the LDN form and updated the latest version of the information, please check it out.

**Comment by szalongdzyxgs** [comment]
Sincerely, we hope to see you support us again.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
@nicelove666 deals are found here for Direct Data Onboarding: https://datacapstats.io/clients/f03138169/ddo-deals

**Comment by nicelove666** [comment]
After the first round of 256T was used up, the bot was not triggered. We think it was a data delay.
After the second round of 512T was used up, the bot was still not triggered. We think it may be due to data delay or the bot may not be working.
Now the bot is still not triggered.
We will no longer sign for this LDN. If you still need it, please apply again.
@szalongdzyxgs

**Comment by filecoin-watchdog** [comment]
@nicelove666 which bot are you talking about? CID checker? It will not run on Direct Data onboarding unfortunately. You have to look at the deals in other ways.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
How would you improve your search for Spark? @szalongdzyxgs

**Comment by szalongdzyxgs** [comment]
We are actively following the progress of Spark https://github.com/space-meridian/roadmap/issues/113, and notifying SPs to make relevant improvements based on Spark. In order to support Spark, we reject all SPs using venus (venus does not support Spark). Currently, we already have one SP making progress on Spark.

**Comment by szalongdzyxgs** [comment]
![WX20240622-090212@2x](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/111476424/c8b6f673-275f-4a73-a0f0-a7fd79f1ebdc)

**Comment by szalongdzyxgs** [comment]
checker:manualTrigger

**Comment by szalongdzyxgs** [comment]
Can you sign us up for another round?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
It seems that the spark date has not improved. Sorry, I may not be able to help you sign another round for the time being.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
@szalongdzyxgs Congratulations, the spark data has been improved. You disclosed 7 sps, but cooperated with 8 sps. Please list the company and location of f03144077.
<img width="1168" alt="WX20240709-115830@2x" src="https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/129046880/13342973-f631-4193-9bf5-e48b4989aa86">

**Comment by nicelove666** [comment]
Any updates here?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Please explain why the support for the "spark" retrieval is 87.5%, otherwise I will not support you.

**Comment by szalongdzyxgs** [comment]
Dear , @nicelove666 f03144077 is located in hk and belongs to Coffee Cloud.
After receiving your message, we immediately contacted SP. Some SP machines and equipment were damaged and are being actively repaired.
We will actively monitor their progress.
Sincerely, we hope you can help us again

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin

**Comment by szalongdzyxgs** [comment]
Are we eligible for continued support?

**Comment by szalongdzyxgs** [comment]
@nicelove666

**Comment by nicelove666** [comment]
Yes, but the data doesn't look good.

**Comment by szalongdzyxgs** [comment]
Can you assign DC to us? @nicelove666

**Comment by nicelove666** [comment]
The search rate is too low, so we are temporarily unable to continue supporting it.
You can recommend a company to apply, thank you.
