### ISSUE TITLE
[DataCap Application] DangBei

### ISSUE THREAD

**Issue by Dangbei1** [nicelove666/Allocator-Pathway-IPFSTT#34]
### Version

1

### DataCap Applicant

DangBei

### Project ID

DangBei01

### Data Owner Name

DangBei

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://www.dangbei.com/

### Social Media Handle

https://www.dangbei.com/

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

640TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f14upg5eq7bevexm6pesc6al5pcbbofdvilolwwui

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
DangBei was founded in August 2013 and is currently one of the well-known smart big-screen value-added service providers in China. It is committed to becoming the core entry point and home entertainment center for millions of households. The company consists of the headquarters in Hangzhou and a branch in Shenzhen, and is an Internet platform company that spans the entire ecosystem of software, hardware, and operating systems.

The company's software services more than 200 million household users, and owns the big-screen app distribution platform Dangbei Market, as well as high-quality big-screen apps such as Dangbei Video, Dangbei Music, Dangbei Desktop, Dangbei Fitness, and Dangbei Projection. In addition, it also provides Dangbei Pay and Dangbei Point SDK services for hundreds of millions of big-screen apps. Leveraging advanced AI capabilities, it provides refined user profiling, not only offering powerful traffic monetization services for developers, but also helping advertisers achieve precise marketing.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
dangbei's products
Design manuscripts and articles
developed software
Film and television resources cooperated with dangbei, content updated and recorded every month
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1_ZX_CtpRvP4ZmDTS_H9GMFMdvZ5YcaRM?usp=drive_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

1.5 to 2 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f01422327 - Japan
f02252023 - Japan
f02252024 - Japan
f01989013 - Malaysia
f01989014 - Malaysia
f01989015 - Malaysia
f02105010 - Malaysia
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:

You need to provide comprehensive SP information, including SP, geographical location, and company name.
Why do you want to put the data on Filecoin?  Do you have relevant data processing experience?
Can you satisfy spark retrieval and store unseal files?

**Comment by nicelove666** [comment]
Can you send us an email using your domain email doris@ipfstt.com @Dangbei1

**Comment by Dangbei1** [comment]
Thanks, we sent the email
![WechatIMG1739](https://github.com/nicelove666/Allocator-Pathway-IPFSTT/assets/173661416/ffa41568-1d1d-4e55-bc3e-f527d9bf6fc3)
This our comprehensive SP information：
f01989013-Malaysia-Milk computing power
f01989014-Malaysia-Milk computing power
f01989015-Malaysia-Milk computing power
f02105010 - Malaysia-Milk computing power
f03144077 - HK- Lemon Cloud
f01422327 - Japan-Asuka Data
f02252023 - Japan-Asuk Data
f02252024 - Japan-Asuk Data
Companies in our industry generate a lot of data, and Alibaba Cloud's storage is relatively expensive. We want to try using Filecoin for storage.
we can satisfy spark retrieval and store unseal files
We have filled it out, please check it out https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose

**Comment by Dangbei1** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
I observed that you have finished using it. If you need my signature, you need to provide evidence of compliance.

**Comment by Dangbei1** [comment]
[ipfstt_34_batch_1.xlsx](https://github.com/user-attachments/files/16061801/ipfstt_34_batch_1.xlsx)

**Comment by Dangbei1** [comment]
trigger:run_retrieval_test URL

**Comment by myfil512** [comment]
Error: No valid URL found in the comment.

**Comment by Dangbei1** [comment]
[ipfstt_34_batch_1.csv](https://github.com/user-attachments/files/16061839/ipfstt_34_batch_1.csv)

**Comment by Dangbei1** [comment]
trigger:https://github.com/user-attachments/files/16061839/ipfstt_34_batch_1.csv

**Comment by Dangbei1** [comment]
trigger:run_retrieval_test https://github.com/user-attachments/files/16061839/ipfstt_34_batch_1.csv

**Comment by myfil512** [comment]
| miner_id | dc_usage_percentage | retrieval_rate | retrieval_success_counts | retrieval_fail_counts |
| --- | --- | --- | --- | --- |
| f01422327 | 7% | 95% | 19 | 1 |
| f01989013 | 19% | 0% | 0 | 20 |
| f01989014 | 19% | 85% | 17 | 3 |
| f01989015 | 19% | 95% | 19 | 1 |
| f02105010 | 19% | 95% | 19 | 1 |
| f02252023 | 7% | 90% | 18 | 2 |
| f02252024 | 7% | 100% | 20 | 0 |

**Comment by nicelove666** [comment]
Please improve on "f02252024" retrieval

**Comment by joshua-ne** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Can you explain why SP is not counted by spark?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by Dangbei1** [comment]
[ipfstt_34-7-15.csv](https://github.com/user-attachments/files/16282344/ipfstt_34-7-15.csv)

**Comment by Dangbei1** [comment]
trigger:run_retrieval_test https://github.com/user-attachments/files/16282344/ipfstt_34-7-15.csv

**Comment by Dangbei1** [comment]
trigger:run_retrieval_test https://github.com/user-attachments/files/16282344/ipfstt_34-7-15.csv

**Comment by myfil512** [comment]
| miner_id | dc_usage_percentage | retrieval_rate | retrieval_success_counts | retrieval_fail_counts |
| --- | --- | --- | --- | --- |
| f01422327 | 10% | 100% | 20 | 0 |
| f01989013 | 17% | 85% | 17 | 3 |
| f01989014 | 17% | 100% | 20 | 0 |
| f01989015 | 17% | 100% | 20 | 0 |
| f02105010 | 17% | 100% | 20 | 0 |
| f02252023 | 10% | 100% | 20 | 0 |
| f02252024 | 10% | 100% | 20 | 0 |

**Comment by nicelove666** [comment]
Sorry, as we said on the call, we are temporarily unable to support you until your SP supports Spark.

I'm looking forward to the network upgrade on August 6th.

**Comment by Dangbei1** [comment]
Hi @nicelove666 , since the network upgrade earlier this week, we have asked our collaborating SP's to fully support Spark retrieval and they've indeed changed their sealing routine and publish their deal info through indexer. So we are looking forward to onboard more data soon, please help.

**Comment by nicelove666** [comment]
I will sign 256T to verify whether what you said is true.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Our team cannot accept CID from cilents and SPs.
We have told you in detail on whatsapp that we can no longer sign for you .

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Closed due to cid sharing
