### ISSUE TITLE
[DataCap Application] Gechuang Dongzhi Technology Co., Ltd.

### ISSUE THREAD

**Issue by olh-a11y** [nicelove666/Allocator-Pathway-IPFSTT#49]
### Version

1

### DataCap Applicant

olh-a11y

### Project ID

getech

### Data Owner Name

Gechuang Dongzhi Technology Co., Ltd.

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://getech.cn/

### Social Media Handle

https://getech.cn/

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

7PiB

### Expected size of single dataset (one copy)

1024TiB

### Number of replicas to store

7

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f14jvqfbgsd26mhsq4ncntygxf3qwh6copyxib55y

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Gechuang Dongzhi Technology Co., Ltd. was established in 2018 and has three core industries: semiconductor display, new energy photovoltaic and semiconductor materials, and intelligent terminals. Gechuang Dongzhi adheres to the "production site-oriented" research and development direction, uses standardized platforms, industrial applications and industry solutions to meet the needs of manufacturing enterprises for intelligence, and is committed to the research and development and innovation of factory intelligent operating systems.

Relying on core technical capabilities such as AI, cloud computing, and big data, Gechuang Dongzhi adheres to the strategy of integrating software and hardware, uses software and algorithms to drive the intelligent upgrade of equipment and edge control hardware, and develops an industrial intelligent product system that integrates software and hardware.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
ai data
manufacturing data
production data
Logistics data, etc.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://drive.google.com/drive/folders/1iuJe-qtElwV530AMyQf9oGj3vBQNw2m3?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03202108  HK
f03157905  GuangDong
f03157910  GuangDong
f09693     Sichuan
f03078786  Dongguan
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:

You need to provide comprehensive SP information, including SP, geographical location, and company name.
Why do you want to put the data on Filecoin? Do you have relevant data processing experience?
Can you satisfy spark retrieval and store unseal files?

**Comment by nicelove666** [comment]
Dear corporate user, thank you for your application.
Is there any update here?
Are you having any difficulties and need our help?
Could you please send us a domain name email (doris@ipfstt.com) to confirm your identity?

**Comment by olh-a11y** [comment]
We have sent an email, please check it.
We still need time to confirm the information about SP.
Can we contact you after we confirm it? Thank you.

**Comment by olh-a11y** [comment]
https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/6 we fill it, thanks

**Comment by olh-a11y** [comment]
Tang Computing f03202108 HK
shensuyun f03157905 GuangDong
shensuyun f03157910 GuangDong
individual investor f09693 Sichuan
individual investor f03078786 Dongguan

All our sps support spark retrieval.We are ready now. @nicelove666

**Comment by nicelove666** [comment]
We had received the email and will send it to the governance team

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
It doesn't look good

**Comment by olh-a11y** [comment]
checker:manualTrigger

**Comment by olh-a11y** [comment]
The bot data has not been updated,

**Comment by olh-a11y** [comment]
<img width="559" alt="WX20241001-162353@2x" src="https://github.com/user-attachments/assets/49b3e129-f0c4-428e-b835-00576663479a">

**Comment by olh-a11y** [comment]
checker:manualTrigger

**Comment by olh-a11y** [comment]
The data has been updated and we hope to get your help.
In the next round we will add US SP f03215853 and f03218576

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
We are happy to see that you have found the US SP.
However, these two SPs were not disclosed in advance and do not support spark. Can you explain?
<img width="1181" alt="WX20241004-212439@2x" src="https://github.com/user-attachments/assets/65c9c040-3901-4e67-984a-41bb1312f01d">

**Comment by olh-a11y** [comment]
Yes, we found SPs from US, they are all brand new SPs, so the spark data is not displayed,  you will see the data update soon.

**Comment by olh-a11y** [comment]
f03157910 China
f03157905 China
f03215853 United States
f03218576 United States
f03202108 HK
f01125521 HK

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
There are two US SPs, one already supports Spark, and the other does not.
It seems that you have encountered some problems and solved some of them, but there are still 50% that have not been solved. Do you need help from our technical team?

**Comment by olh-a11y** [comment]
We are actively communicating with SP. f03218576 has been debugged successfully and the spark data will be updated soon. @nicelove666

**Comment by olh-a11y** [comment]
checker:manualTrigger

**Comment by olh-a11y** [comment]
<img width="1172" alt="WX20241008-085626@2x" src="https://github.com/user-attachments/assets/0bc7fa7f-931a-4d3a-bee4-8b5b02be3ebd">

**Comment by olh-a11y** [comment]
Happy to get the update.

**Comment by nicelove666** [comment]
Glad to see the update. Already supporting the next round.
US SPs have increased their geographic diversity, which is very consistent with FIL+ requirements. We hope you can contact us, and we will ask SPs whose geographic locations are only in mainland to send DCs to US SPs for free.

**Comment by nicelove666** [comment]
doris@ipfstt.com

**Comment by olh-a11y** [comment]
checker:manualTrigger

**Comment by olh-a11y** [comment]
We have contacted you and hope you can give more DC to US SP.
Our f03159705 machine has some problems and is being urgently restored to 75%-- Spark .

**Comment by olh-a11y** [comment]
Now, our 2P has been used up, and we hope to get your help, thank you.

**Comment by olh-a11y** [comment]
@nicelove666

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
![WechatIMG24299](https://github.com/user-attachments/assets/bbb03144-9dee-4d14-9069-3d7e02d6f665)

**Comment by nicelove666** [comment]
What happened to 7905?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by udi1231239** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
The spark support rate of 7905 needs to be improved.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Sorry to have kept you waiting for so long. 
Congratulations, 7905 has been improved.  let 7905 arrived 75%.

**Comment by nicelove666** [comment]
After we confirmed the signature, we waited for 6 minutes,  https://allocator.tech/ showed that the signature was successful, but it was not displayed on GitHub. we checked on lotus and it was not received. Recently, the gas of the filecoin network has fluctuated greatly. Is the gas is too high, or do we need to wait? Thanks for helping us check it.
<img width="1209" alt="WX20241014-103608@2x" src="https://github.com/user-attachments/assets/9bf8341f-521c-43bd-8e10-cdb11a6d52fc">

**Comment by nicelove666** [comment]
@filecoin-watchdog @willscott Please help me take a look

**Comment by Filip-L** [comment]
@nicelove666 Thank you for reporting. Please don't issue any DataCap for this client until we provide a fix. Should be done tomorrow.

**Comment by nicelove666** [comment]
thanks

**Comment by nicelove666** [comment]
Thank you for your contribution @Filip-L @kacperzuk-neti

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by olh-a11y** [comment]
We meet a customer who borrowed and pledged money from haven, so we want to increase the total amount. Please approve it, @nicelove666

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
The retrieval success rate is very high, and it seems to be relatively standardized.We are not sure whether we can approve your request to increase the total DC quota. We will seek the answer from the governance team. Please wait.

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
You want to increase the total amount of data.
We don't know how much data your company has?
So, please provide more data cases to prove it.

**Comment by nicelove666** [comment]
If there are no updates here, we want to turn off.
