### ISSUE TITLE
[DataCap Application] ePublishing

### ISSUE THREAD

**Issue by usejsi** [nicelove666/Allocator-Pathway-IPFSTT#51]
### Version

1

### DataCap Applicant

ePublishing

### Project ID

ePublishing001

### Data Owner Name

ePublishing

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.epublishing.com/about/

### Social Media Handle

https://www.epublishing.com/about/

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10PiB

### Expected size of single dataset (one copy)

1PiB

### Number of replicas to store

10

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1blcdr5udxdsxls6wvltwv46eo4iyivxmhhfsniy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
ePublishing is an integrated modern media tech stack driving revenue, improving productivity, and increasing engagement for publishers of content and data. They streamline editorial and audience workflows, amplify content delivery, diversify and grow revenue, and leverage a unified, data-first publishing ecosystem.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data being stored are the archives and historical editorial and images from media companies - from daily newspapers to monthly magazines - that may reach back as far as 100 years.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Canada

### Please share a sample of the data

```text
https://i.imgur.com/P4eoAZw.png

Sample image used in a old new york times article, one that epublishing manages and stores.
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), IPFS, Shipping hard drives, Lotus built-in data transfer

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03179570 SINGAPORE
f02826253 SINGAPORE
f02826815 HK
f03151449 SHENZHEN
f03151456 SHENZHEN
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:

You need to provide comprehensive SP information, including SP, geographical location, and company name.
Why do you want to put the data on Filecoin? Do you have relevant data processing experience?
Can you satisfy spark retrieval and store unseal files?

**Comment by usejsi** [comment]
https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/4

**Comment by usejsi** [comment]
DataPulse f02838518  Moscow, Moscow, RU   
Insightrix f02832475  Bangkok, Bangkok, TH
DataNova f02859053 Hanover, New Jersey, US
IntelliSphere f02826253 SINGAPORE
ShuJie f02826815 HK
YunXi  f03151449 SHENZHEN
YunXi  f03151456 SHENZHEN

**Comment by usejsi** [comment]
We have enough experience in data processing, our team is already downloading data, and we have developed our own data software to prevent CID sharing. In addition, we have checked that all the SPs we work with support Spark retrieval.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
Hello, the quota has been used up, can you help us?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Can you explain why this SP does not support spark?<img width="1160" alt="WX20240909-132353@2x" src="https://github.com/user-attachments/assets/bfd6c699-7dd5-4e0a-8bdb-151ce9859e37">

**Comment by usejsi** [comment]
@nicelove666  f03179570 is a new SP. We all know that SP needs to wait for time after registration before it can be displayed on spark. And the quota for the first round is only 256T. I hope you can sign the second round for us. We believe that the data at that time will see a significant improvement.
Thank you!

**Comment by usejsi** [comment]
We modified the sp of the application form yesterday. Since this is the first round, we changed the sp information and hope to get your support. Sincerely, our DC has been used up and we look forward to your help.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
There are too many duplicate data, and the retrieval rate of some sp is less than 20%. Although we understand that this is the first round, the amount of data is relatively small and not enough to feedback all the situations. However, we cannot sign for you again, sorry

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
> There are too many duplicate data, and the retrieval rate of some sp is less than 20%. Although we understand that this is the first round, the amount of data is relatively small and not enough to feedback all the situations. However, we cannot sign for you again, sorry

I'm really sorry, this may be a technical error.
But we only got the first round of 256T,
Can you give us another chance to sign 512T for us?

**Comment by nicelove666** [comment]
Since yours is a new account, the trust value is relatively low, and many problems have occurred, so I'm sorry that I can't sign for you.

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
以下是您提供内容的英文翻译：

---

The retrieval rate of Spark continues to improve.

The issue with data backup is that the first round only has 256T, which is too little.

If you could sign us up for the next round, we would definitely be able to solve the data backup issue and continuously improve the Spark retrieval rate.

If the data backup issue is not resolved in the next round and you no longer sign for us, we can understand.

Sincerely, thank you.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Congratulations, your data has been updated, spark is looks good, we will sign it for you later.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
<img width="1139" alt="WX20241011-175322@2x" src="https://github.com/user-attachments/assets/1b6ca427-dc56-4790-be1f-88ae63dadc4f">

**Comment by nicelove666** [comment]
Congratulations, the spark retrieval rate has been improved. Please continue.
The cooperation SP and disclosure SP are inconsistent, please explain.

**Comment by usejsi** [comment]
In order to let you to support us quickly (the last round of signatures took about 25 days to wait), we strictly require SP to store files. We borrow FIL, so we hope to get it as soon as possible.

**Comment by usejsi** [comment]
It has been more than a month since we submitted the application. During this period, we have contacted new SPs, so we added 3 SPs, they are f02825282 (HK), f03178144 (JP), and f03214937 (US).

**Comment by usejsi** [comment]
Hope to get support quickly.

**Comment by usejsi** [comment]
@nicelove666 just wanted to let you know that we have been waiting too long.

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
Thank you, we will add f03178144 Tokyo；f02826588 shenzhen

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Considering that the dataset is stored multiple times, we cannot sign for you. If you need continued support, please find a new dataset.
We need to understand that storing the data multiple times can not help the growth and development of the Filecoin network.

**Comment by usejsi** [comment]
What we need to do to continue to get your support @nicelove666

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin

**Comment by usejsi** [comment]
checker:manualTrigger

**Comment by usejsi** [comment]
We applied for 10P in total, but only got a little. Please continue to approve it, thank you.

**Comment by nicelove666** [comment]
Your data doesn't look very good, and according to our rules, we will reject you directly.
However, following the guidance of the governance team, we will focus on supporting old customers in this round.
If you can bring us enterprise customers onboarding, or you can bring us a brand new data set, we can also continue to support you, thank you.

**Comment by usejsi** [comment]
just want to know, is this ldn no longer get support?

**Comment by usejsi** [comment]
#96 We have resubmitted as per your request, can we continue to receive support?

**Comment by usejsi** [comment]
Can I still get help here?

**Comment by nicelove666** [comment]
We provide support for your new application 96.

**Comment by usejsi** [comment]
thanks

**Comment by Trevor-K-Smith** [comment]
Hello, ePublishing is a private client of ours. We recently talked to them and there is no relationship between them and this application. We have went through KYB checks with client and have custom pipeline sealing their data.

Im confused on why this application exists and why you are claiming to have stored data for them? It is not a public dataset and looks like you copied our original application here - https://github.com/fidlabs/Enterprise-Data-Pathway/issues/43

This application is undermining our relationship by making it appear as if client data is being put on unapproved miners and locations.

@nicelove666

**Comment by filecoin-watchdog** [comment]
@usejsi Please, take a look at the comment above and explain your actions here. If the data are private, what are you storing instead? 
I’m waiting for your explanation regarding the data matter. In the meantime, I’d like to point out that copying someone else’s application is considered inappropriate.
