### ISSUE TITLE
[DataCap Application] <Allen Institute> - <open data> 

### ISSUE THREAD

**Issue by Timothea01** [nicelove666/Allocator-Pathway-IPFSTT#53]
### Version

1

### DataCap Applicant

Allen Institute

### Project ID

1

### Data Owner Name

Allen Institute

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Life Science / Healthcare

### Website

https://registry.opendata.aws/?search=managedBy:allen%20institute

### Social Media Handle

Timothea01

### Social Media Type

Other

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

348TiB

### Number of replicas to store

6

### Weekly allocation of DataCap requested

2PiB

### On-chain address for first allocation

f1ifaqhylvx24mthmjjmro643vs75hapf5agu7qoy

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
I'm the tech lead for pubang and would like to bring more public data to filecoin
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
aws s3 ls --no-sign-request s3://allen-brain-observatory/   158.8 TiB
aws s3 ls --no-sign-request s3://allen-mouse-brain-atlas/ 190.0 TiB
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

Hong Kong

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We use Lotus Boost and singularity to prepare the data
```

### Please share a sample of the data

```text
aws s3 ls --no-sign-request s3://allen-brain-observatory/   158.8 TiB
aws s3 ls --no-sign-request s3://allen-mouse-brain-atlas/ 190.0 TiB
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Daily

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:

You need to provide comprehensive SP information, including SP, geographical location, and company name.
Why do you want to put the data on Filecoin? Do you have relevant data processing experience?
Can you satisfy spark retrieval and store unseal files?

**Comment by Timothea01** [comment]
>You need to provide comprehensive SP information, including SP, geographical location, and company name.

f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong

All are affiliated with individuals, not corporations

>Why do you want to put the data on Filecoin? 

Contribute to it

>Do you have relevant data processing experience?

yes,we use Lotus Boost and singularity to prepare the data

>Can you satisfy spark retrieval and store unseal files?

All support

**Comment by Timothea01** [comment]
checker:manualTrigger

**Comment by Timothea01** [comment]
It looks like the CID bot data isn't updated in real time

**Comment by Timothea01** [comment]
Can I apply for the next round of approvals now?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by Timothea01** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
We observed that after the first round was used up, it was basically difficult for the bot to be triggered before signing,  the amount of the first round was relatively small and used up quickly, but the bot needed time to update. We use the same standard for all applicants (customers):
First round: 256T
Second round: 512T
Third round: 1P
After the first round was used up, if there was no bot data, our team would manually evaluate the customer and sign the second round.
However, if the bot has not been updated after the second round was used up, we will no longer be able to support the third round until the data is updated.
We have many customers who waited for 1 month between the second and third rounds, and we signed only after the bot data was updated.
Finally, the above rules apply to all customers and SPs in IPFSTT.

**Comment by Timothea01** [comment]
Got it

**Comment by Timothea01** [comment]
The sp we worked with in the first round was consistent with what was announced
f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong

**Comment by Timothea01** [comment]
![image](https://github.com/user-attachments/assets/eed673d8-ed8a-4875-ac6f-083e0fe2bf58)
Data from [third-party websites](https://ehume.com/#/clientDetail?clientAddress=f1ifaqhylvx24mthmjjmro643vs75hapf5agu7qoy&dataCapConsumeStr=237%20TB&dataCapReleasedStr=256%20TB&dataCapTotalStr=256%20TB&dataCapNotConsumeStr=19%20TB)

**Comment by Timothea01** [comment]
checker:manualTrigger

**Comment by Timothea01** [comment]
Can you apply for the next round of approvals now?

**Comment by nicelove666** [comment]
Disclosure SP and actual cooperation SP are the same
All SPs support Spark
The overall success rate of SPs has reached 70%
Hope to see the data of SPs supporting Spark reach 75%, you are very close to the goal, come on!

**Comment by Timothea01** [comment]
thanks

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by Timothea01** [comment]
checker:manualTrigger

**Comment by Timothea01** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Our team has received your recharge requests many times.
You have done a lot of good things:
1. The SP disclosed is the same as the actual SP
2. All SPs support Spark
However, you also have some problems:
1. SP support for Spark does not reach 75%
2. Some SPs store duplicate data.
Therefore, we cannot sign for you for the time being.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
It looks like the data has been updated. I can sign another 256T for you.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
> It looks like the data has been updated. I can sign another 256T for you.
Considering that the dataset is stored multiple times, we cannot sign for you. If you need continued support, you need find a new dataset.
We need to understand that storing the data multiple times can not help the growth and development of the Filecoin network.

**Comment by nicelove666** [comment]
> It looks like the data has been updated. I can sign another 256T for you.

Considering that the dataset is stored multiple times, we cannot sign for you. If you need continued support, you need find a new dataset.
We need to understand that storing the data multiple times can not help the growth and development of the Filecoin network.

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin
