### ISSUE TITLE
[DataCap Application] <K12 International > - <teaching material>

### ISSUE THREAD

**Issue by 1613557499** [nicelove666/Allocator-Pathway-IPFSTT#58]
### Version

1

### DataCap Applicant

Dataset Owner

### Project ID

1

### Data Owner Name

孙隼

### Data Owner Country/Region

China

### Data Owner Industry

Education & Training

### Website

http://www.topschools.cn/index

### Social Media Handle

顶思

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

1PiB

### Expected size of single dataset (one copy)

256

### Number of replicas to store

4

### Weekly allocation of DataCap requested

512TiB

### On-chain address for first allocation

f1vnjg55b2vpja36bzx6aiyz2nqrshcbgq3nre3eq

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
TopSchools was founded on August 28, 2016.  As the resource aggregation platform of K12 international Education, TopSchools is committed to supporting the sustainable development of the international school market through community communication, data research, teacher training and talent recruitment.  Topschools is a close partner of international schools and international education institutions.  Provides industry with information on international education policies, operations, investments, schools, and people.  Organized various online and offline activities, cooperated with various examination bureaus, global top universities, research institutions, embassies and consulates, and provided services and support for more than 600 schools across the country;  We are linked to thousands of quality school service providers around the world to provide a variety of solutions for schools.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Our data is very large, mainly stored all kinds of courses of teaching videos, materials, documents.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We plan to cooperate and negotiate with professionals to ensure the safety and reliability of data, and achieve short-term or long-term effective storage to ensure the integrity of data
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no，the company's development is stable, our data is always growing, storage costs are also increasing, the need for filecoin network support, for the development of the traditional Internet industry to promote.
```

### Please share a sample of the data

```text
https://pan.baidu.com/s/1vOQ-h6lCCLvCXAY_PtsP1A?pwd=6jt9 
https://pan.baidu.com/s/1CbRHk1E-tiXULoJIgLawMw?pwd=iapx 
https://pan.baidu.com/s/1_qSCseiHfUPyXFumfgvsLQ?pwd=fgis
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Africa, North America, South America, Europe, Australia (continent)

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS, Lotus built-in data transfer, Venus built-in data transfer

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03143698，香港
f03143705，上海
f0870354，新加坡
f01989372，香港
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Droplet client, Bidbot, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
https://github.com/fidlabs/Open-Data-Pathway/issues/37
https://github.com/fidlabs/Open-Data-Pathway/issues/76
K12 has applied here twice, and willscott of PL has closed your application.
We think that any company can only apply for DC once.
However, K12 also applied multiple times during the v3-v4.
Sorry, we can not support you for the time being.
<img width="1225" alt="WX20240920-131936@2x" src="https://github.com/user-attachments/assets/685ba990-7229-4e95-a73b-ca563f50f23c">
