### ISSUE TITLE
[DataCap Application]  EMPIAR

### ISSUE THREAD

**Issue by nike-mp** [nicelove666/Allocator-Pathway-IPFSTT#7]
### Version

1

### DataCap Applicant

FileTech

### Project ID

FileTech-EMPIAR

### Data Owner Name

EMPIAR

### Data Owner Country/Region

United Kingdom

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.ebi.ac.uk/empiar/

### Social Media Handle

https://www.ebi.ac.uk/empiar/

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

10

### Unit for total amount of DataCap being requested

PiB

### Expected size of single dataset (one copy)

2

### Unit for expected size of single dataset

PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

250

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1ayjwaeyndyq6in5ykvu6y2zutrsaps3fm5af7pa

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
FileTech focuses on providing excellent data storage solutions. We have a passionate and knowledgeable team with extensive experience and expertise in the field of data storage. Whether it's data storage, data management, data recovery, or data center design and construction, we possess abundant technical capabilities and solutions.

At FileTech, we understand the importance of data in modern businesses. We not only offer high-performance data storage devices and solutions, but also provide comprehensive data management tools to help clients efficiently organize, classify, and protect their data assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
EMPIAR, the Electron Microscopy Public Image Archive, is a public resource for raw images underpinning 3D cryo-EM maps and tomograms (themselves archived in EMDB). EMPIAR also accommodates 3D datasets obtained with volume EM techniques and soft and hard X-ray tomography. More ...
As of 2023-04-02， EMPIAR contains 1627 entries, taking up 4.04 PB of storage.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### Please share a sample of the data

```text
https://www.ebi.ac.uk/empiar/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How did you find your storage providers

Slack, Filmine

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02984282 
f02942808
f02894875
f02370792 
f01025366
f0122215 
f0427989
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Bidbot

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Have you ever applied for the same DC as the previous LDN?
Have you been assigned all the previously applied DCs?
Please let me know the link of the LDN I applied for the same content as before.
Are you ready? Do you need technical help from our team?

**Comment by nike-mp** [comment]
hi,
