### ISSUE TITLE
[DataCap Application] <MODRONS' LAW> - <MODRONS'LAW-EUD-1>

### ISSUE THREAD

**Issue by Dengminer** [nicelove666/Allocator-Pathway-IPFSTT#72]
### Version

1

### DataCap Applicant

MODRONS' LAW

### Project ID

MODRONS'LAW-EUD-1

### Data Owner Name

European Union

### Data Owner Country/Region

Luxembourg

### Data Owner Industry

Government

### Website

https://data.europa.eu/

### Social Media Handle

X: https://x.com/EU_opendata

### Social Media Type

Twitter

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

5 PiB

### Expected size of single dataset (one copy)

1 PiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

800 TiB

### On-chain address for first allocation

f1cx4a3awirb4nkxw5isxxa5rt2xafjflbnx3cmzq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
At Modrons' Law, we believe that rules and laws are the fundamental principles governing the world, and that the mechanical paradigm is the key to the advancement of civilization. Humanity is progressively deepening its understanding of these principles, categorizing them into various scientific disciplines. As civilization evolves by emulating these principles—whether socially or mathematically—our comprehension of the world's rules is both validated and enhanced. Our mission is to drive this emulation forward in the field of computer science, fostering innovation and progress.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The European Data organization, led by the EU, offers a broad range of datasets across various fields, such as environment, economy, healthcare, and demographics. These datasets support research, policy-making, and innovation, aiming to increase transparency and stimulate growth through data-driven approaches. The data is designed for easy use across different sectors and regions within the EU.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### Please share a sample of the data

```text
https://data.europa.eu/data/datasets/b0203a76-ab90-4564-9789-9b7c21fb9c65~~1
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Asia other than Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Shipping hard drives

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03215853, US
f03218576, US
f03220176, HongKong
f03157910, Guangdong, China
f03224283, Japan
f03224551, Japan
f03230392, Vietnam
f03230423, Malaysia
f03232064, Malaysia
f03232134, Malaysia
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Dengminer** [comment]
Hi, I have filled the diligence form as in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/9. 

The SP information is provided in the application form. We want to put the data on Filecoin because it's cheap, reliable, and will work with web3 applications. And yes, we have experience in onboarding data to Filecoin network and we confirm that we will only work with SP's who support SPARK retrieval and who always store hot copies of the data. 

Please let me know if you have any further questions.

**Comment by nicelove666** [comment]
Could you tell us how do you prepare the data? Thank you!

**Comment by Dengminer** [comment]
Sure, so basically we have a set of homemade tools to combine or split the original data files to appropriate sizes, usually around 34GB, as preferred by SP's. And then we use our scripts to convert the data into .car files and deliver to SP's. Please let us know if you have additional questions.

**Comment by Dengminer** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
We cannot sign for you until f03220176 supports spark

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
There are only 3 SPs in the first round. Will the number of SPs increase in the next round?

**Comment by Dengminer** [comment]
Definitely, we will onboard more SP's in the following round.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Need add more SP, such as more regions and more quantities

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
The bot data has not been updated and cannot sign for you.

**Comment by Dengminer** [comment]
Now we have onboarded 4 SP's and the retrieval rate has significantly been improved, as can be seen here:
https://ehume.com/#/clientDetail?clientAddress=f1cx4a3awirb4nkxw5isxxa5rt2xafjflbnx3cmzq&dataCapConsumeStr=710.71%20TB&dataCapReleasedStr=1.75%20PB&dataCapTotalStr=1.75%20PB&dataCapNotConsumeStr=1.05%20PB

Please support for the next round.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by Dengminer** [comment]
We are working with another 4 SP's listed below. Please help approve, thanks!

f03230392 - Vietnam
f03230423 - Malaysia
f03232064 - Malaysia
f03232134 - Malaysia

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Hope to see more improvements

**Comment by Dengminer** [comment]
checker:manualTrigger

**Comment by Dengminer** [comment]
We have used up all the DC. We work very closely with our collaborating SPs to make sure they are publicly retrievable and, ideally support SPARK well. So far, all the retrieval data checks good from our end, please let us know if there are any issues and we will communicate with the SP's to work them out. 

We have a small batch of data needs to be onboarded with current SPs. Please support with another small batch. Thank you very much.

**Comment by Dengminer** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Fix the retrieval rate of f03224283, then we sign

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
According to the guidance of the governance team, this round will mainly focus on assisting existing clients. Please provide a detailed description of your technical solutions, market capabilities, and what new data you can bring to Filecoin

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
checker:manualTrigger
