### ISSUE TITLE
[DataCap Application] <Dazhu County Wannongda agricultural development limited liability company> - <agriculture> 

### ISSUE THREAD

**Issue by jauea** [nicelove666/Allocator-Pathway-IPFSTT#74]
### Version

1

### DataCap Applicant

Dazhu County Wannongda agricultural development limited liability company

### Project ID

1

### Data Owner Name

Dazhu County Wannongda agricultural development limited liability company

### Data Owner Country/Region

China

### Data Owner Industry

Resources, Agriculture & Fisheries

### Website

www.wannongda.net

### Social Media Handle

www.wannongda.net

### Social Media Type

Other

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

3PiB

### Expected size of single dataset (one copy)

350TiB

### Number of replicas to store

8

### Weekly allocation of DataCap requested

2PiB

### On-chain address for first allocation

f1kqnifax2s37vot34zweny7hl42drzxt37w5qhfq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
General projects: spice crop cultivation; Fruit cultivation; Tea planting; Vegetable cultivation; Nut cultivation; Bean planting; Tobacco cultivation; Sugar crop cultivation; Tree planting and management; Fertilizer sales; Agricultural machinery sales; Agricultural film sales; Conference and exhibition services; Marketing of pesticides for health use; Livestock and fishery feed sales; Sales of agricultural and sideline products; Sales of forestry products; Primary processing of edible agricultural products; Wholesale of edible agricultural products; Retail of edible agricultural products; Fresh vegetable wholesale; Purchase of primary agricultural products; Sales of specialized machinery for agriculture, forestry, animal husbandry, auxiliary and fishery; Internet sales (except sales of goods that require a license); Installation and maintenance of specialized machinery for agriculture, forestry, animal husbandry and secondary fishery; Crop pest control services; Business agency service; Technical service, technology development, technology consultation, technology exchange, technology transfer, technology.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Various farming techniques.
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
I'm a data preparer and I use Lotus/Boost
```

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
myself
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
no
```

### Please share a sample of the data

```text
https://cloud.189.cn/web/share?code=nEriQzzIFn2i（访问码：cih5）
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, South America, Europe

### How will you be distributing your data to storage providers

HTTP or FTP server, Shipping hard drives

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03166677 Guangzhou
f03166688 Guangzhou
f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong

```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by nicelove666** [comment]
Could you please send us a domain name email ([doris@ipfstt.com] to confirm your identity?

**Comment by nicelove666** [comment]
Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

Our main focus is:

You need to provide comprehensive SP information, including SP, geographical location, and company name.
Why do you want to put the data on Filecoin? Do you have relevant data processing experience?
Can you satisfy spark retrieval and store unseal files?

**Comment by jauea** [comment]
> Thank you for your application, please fill in https://github.com/nicelove666/IPFSTT-Client-Due-Diligence-Form/issues/new/choose.

已填写

> 
> Our main focus is:
> 
> You need to provide comprehensive SP information, including SP, geographical location, and company name. 

f02822222 Hong Kong
f02368946 Beijing
f02362412 California
f02639492 California
f03166666 Hongkong
f03166668 Hongkong

They all belong to individuals

>Why do you want to put the data on Filecoin? 

Data loss can be prevented through distributed storage

>Do you have relevant data processing experience?

Have applied before, processed car documents

 >Can you satisfy spark retrieval and store unseal files?

SPs they all support

**Comment by nicelove666** [comment]
Could you tell us how  do you prepare the data? Thank you!

**Comment by jauea** [comment]
I'm a data preparer and I use Lotus/Boost

**Comment by jauea** [comment]
Is it ready for replenishment?

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by jauea** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
<img width="1091" alt="WX20241010-100223@2x" src="https://github.com/user-attachments/assets/15accf22-02bc-45c7-87e4-96dba354b55e">

**Comment by jauea** [comment]
Can you move on to the next step?

**Comment by jauea** [comment]
checker:manualTrigger

**Comment by jauea** [comment]
The disclosed SP is exactly the same as the actual cooperation. I hope you can continue to get support,thanks！

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by nicelove666** [comment]
Your retrieval rate is around 60%, but FIL+ requires 75%. I hope you can continue to work hard. After signing for you in this round, I hope you can reach 75%.
Why do you want to change the link to the data case?

**Comment by jauea** [comment]
Our colleague uploaded some private content to the previous link. Although we deleted it immediately, we were worried that it would still be viewed, so we set the link to be unavailable (it could be viewed without a password before). Then, we changed the link again. For security reasons, we set a password. You can view it by entering the password. Thank you.

**Comment by nicelove666** [comment]
checker:manualTrigger

**Comment by jauea** [comment]
Two new partners are planned
f03166677  Guangzhou
f03166677  Guangzhou

So the total request will be revised to 3P, The number of copies will be revised to 8,please confirm, thank you!

**Comment by jauea** [comment]
checker:manualTrigger
